from django.contrib import admin

# Register your models here.
from .models import Cardiology, Endocrinology, Ae, Aefobs, Aemaleobs, Aepeadons, Ancclinic, Cardroom, Casualitytheatre, Deliveries, Dental, Dermatology, Dressingroom, Ecg, Ent, Femaleobs, Ffactivities, Fmw, Hts, Icu, Immunization, Injectionroom, Inpatients, Kschma, Laboratory, Lyingwarda, Lyingwardb, Maleopd, Mmw, Msw, Neorology, Neprology, Newa, Nhis, Nursery, Obtetrics, Opthomology, Othopedic, Outpatients, Paed, Paediatricopd, Paediatricsc, Physiotheraphy, Pmctc, Psycatrics, Radiology, Reomatism, Sopd, Theatre


admin.site.register(Cardiology)
admin.site.register(Endocrinology)
admin.site.register(Ae)
admin.site.register(Aefobs)
admin.site.register(Aemaleobs)
admin.site.register(Aepeadons)
admin.site.register(Ancclinic)
admin.site.register(Cardroom)
admin.site.register(Casualitytheatre)
admin.site.register(Deliveries)
admin.site.register(Dental)
admin.site.register(Dermatology)
admin.site.register(Dressingroom)
admin.site.register(Ecg)
admin.site.register(Ent)
admin.site.register(Femaleobs)
admin.site.register(Ffactivities)
admin.site.register(Fmw)
admin.site.register(Hts)
admin.site.register(Icu)
admin.site.register(Immunization)
admin.site.register(Injectionroom)
admin.site.register(Inpatients)
admin.site.register(Kschma)
admin.site.register(Laboratory)
admin.site.register(Lyingwarda)
admin.site.register(Lyingwardb)
admin.site.register(Maleopd)
admin.site.register(Mmw)
admin.site.register(Msw)
admin.site.register(Neorology)
admin.site.register(Neprology)
admin.site.register(Newa)
admin.site.register(Nhis)
admin.site.register(Nursery)
admin.site.register(Obtetrics)
admin.site.register(Opthomology)
admin.site.register(Othopedic)
admin.site.register(Outpatients)
admin.site.register(Paed)
admin.site.register(Paediatricopd)
admin.site.register(Paediatricsc)
admin.site.register(Physiotheraphy)
admin.site.register(Pmctc)
admin.site.register(Psycatrics)
admin.site.register(Radiology)
admin.site.register(Reomatism)
admin.site.register(Sopd)
admin.site.register(Theatre)


