# Generated by Django 2.1.4 on 2018-12-12 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_endocrinology'),
    ]

    operations = [
        migrations.AddField(
            model_name='endocrinology',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
